--- 
title: "JavaScript for Data Science Book Club"
author: "The Data Science Learning Community"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
github-repo: r4ds/bookclub-js4ds
description: "This website is the product of the Data Science Learning Community's JavaScript for Data Science Book Club."
---

# Welcome {-}

Welcome to the JavaScript for Data Science book club! 

This website is a companion for the book [_JavaScript for Data Science_](https://third-bit.com/js4ds/) by Maya Gans, Toby Hodges, and Greg Wilson (copyright January 2020).
This companion is available at [dslc.io/js4ds](https://dslc.io/js4ds).

This website is being developed by the [Data Science Learning Community](https://dslc.io). Follow along, and [join the community](https://dslc.io/join) to participate.

This companion follows the [Data Science Learning Community Code of Conduct](https://dslc.io/conduct).

## Book club meetings {-}

- Each week, a volunteer will present a chapter from the book (or part of a chapter).
  - **This is the best way to learn the material!**
- Presentations will usually consist of a review of the material, a discussion, and/or a demonstration of the principles presented in that chapter.
- More information about how to present is available in the [github repo](https://github.com/r4ds/bookclub-js4ds).
- Presentations will be recorded, and will be available on the [Data Science Learning Community YouTube Channel](https://dslc.io/youtube).

## Pace {-}

- We'll _try_ to cover 1 chapter/week, but...
- ...It's ok to split chapters when they feel like too much.
- We will try to meet every week, but will likely take some breaks for holidays, etc.

## How to present {-}

- The meeting's presentator doesn't need to use the
R **bookdown** package for the chapter slides.

- However, it's **highly beneficial** (for all present and future cohort members)
that the chapter notes are created via `bookdown`.

- If you are comfortable with **R**, you may follow
these [instructions](https://github.com/r4ds/bookclub-js4ds#how-to-present).

- If you are comfortable with **Git** and **GitHub**, you may
follow these alternative steps:
    1. **Fork** this bookclub's GitHub [repository](https://github.com/r4ds/bookclub-js4ds).
    1. From your forked repo, **create a branch** for your notes of the chapter to present.
    1. After saving your finished chapter notes, **add**, **commit** and **push**
    your changes into your forked repo.
    1. Finally, create a **pull request** in order to update the online version of the book.
    1. Pay attention to the messages on GitHub. For example, if your branch is out of date, please merge the main branch and resolve any conflicts (see the [full instructions](https://github.com/r4ds/bookclub-js4ds#how-to-present) for easy ways to deal with things in R).

